# Generated by PolicyTranslator v1.0
# Do not edit manually — regenerate from policy.yaml

# Read-only access to prod DB password
path "secret/data/prod/db-password" {
  capabilities = ["list", "read"]
}

path "secret/metadata/prod/db-password" {
  capabilities = ["list"]
}
