# Vault provider resources — KV engine, auth methods, policies.
# Applied after the VM is up and Vault is initialised.

resource "vault_mount" "kv" {
  path        = "secret"
  type        = "kv-v2"
  description = "KV v2 secrets engine for application secrets"

  options = {
    version = "2"
  }
}

resource "vault_auth_backend" "approle" {
  type = "approle"
  path = "approle"
}

resource "vault_approle_auth_backend_role" "app" {
  backend        = vault_auth_backend.approle.path
  role_name      = "secrets-manager-app"
  token_policies = [vault_policy.app_read.name]
  token_ttl      = 3600
  token_max_ttl  = 86400
}

resource "vault_policy" "app_read" {
  name = "secrets-manager-app-read"

  policy = <<-EOT
    # Auto-generated by Terraform — do not edit manually.

    path "secret/data/prod/*" {
      capabilities = ["read", "list"]
    }

    path "secret/metadata/prod/*" {
      capabilities = ["read", "list"]
    }
  EOT
}

resource "vault_policy" "app_write" {
  name = "secrets-manager-app-write"

  policy = <<-EOT
    path "secret/data/prod/*" {
      capabilities = ["create", "update", "read", "list"]
    }

    path "secret/delete/prod/*" {
      capabilities = ["update"]
    }
  EOT
}

# Audit device — file audit log inside the VM.
resource "vault_audit" "file" {
  type = "file"
  path = "file"

  options = {
    file_path = "/var/log/vault/audit.log"
  }
}
