apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager-app
  namespace: secrets-manager
  annotations:
    # Vault Kubernetes auth — the SA is bound to the Vault role below.
    vault.hashicorp.com/role: "secrets-manager-app"
    # GCP Workload Identity (if running on GKE)
    iam.gke.io/gcp-service-account: "app@PROJECT_ID.iam.gserviceaccount.com"
