"""Unit tests — Phase 3: PolicyTranslator static class."""

from __future__ import annotations

import json

import pytest

from secretsmanager.policy import PolicyTranslator


SAMPLE_YAML = """
version: "1.0"
rules:
  - path: "prod/db/password"
    description: Read prod DB password
    capabilities:
      - read
    principals:
      - type: vault_policy
        id: app-readonly
      - type: aws_iam_role
        id: arn:aws:iam::123456789012:role/app-role
      - type: gcp_service_account
        id: app@my-project.iam.gserviceaccount.com
      - type: azure_sp
        id: "00000000-0000-0000-0000-000000000001"

  - path: "prod/api/*"
    description: Read and list all API secrets
    capabilities:
      - read
      - list
    principals:
      - type: aws_iam_role
        id: arn:aws:iam::123456789012:role/api-role
      - type: gcp_service_account
        id: api@my-project.iam.gserviceaccount.com
      - type: azure_sp
        id: "00000000-0000-0000-0000-000000000002"

  - path: "dev/keys"
    capabilities:
      - write
      - delete
    principals:
      - type: aws_iam_user
        id: ops-engineer
"""


@pytest.fixture()
def doc():
    return PolicyTranslator.load_yaml(SAMPLE_YAML)


@pytest.mark.unit
class TestLoadAndValidate:
    def test_load_yaml_returns_dict(self, doc):
        assert isinstance(doc, dict)

    def test_version_parsed(self, doc):
        assert doc["version"] == "1.0"

    def test_rule_count(self, doc):
        assert len(doc["rules"]) == 3

    def test_validate_passes_on_valid(self, doc):
        PolicyTranslator.validate_yaml(doc)  # should not raise

    def test_validate_missing_rules_raises(self):
        with pytest.raises(ValueError, match="rules"):
            PolicyTranslator.validate_yaml({"version": "1.0"})

    def test_validate_empty_rules_raises(self):
        with pytest.raises(ValueError, match="non-empty"):
            PolicyTranslator.validate_yaml({"rules": []})

    def test_validate_missing_path_raises(self):
        with pytest.raises(ValueError, match="path"):
            PolicyTranslator.validate_yaml({"rules": [{"capabilities": ["read"], "principals": []}]})

    def test_validate_unknown_cap_raises(self):
        with pytest.raises(ValueError, match="unknown values"):
            PolicyTranslator.validate_yaml({
                "rules": [{"path": "x", "capabilities": ["teleport"], "principals": []}]
            })

    def test_validate_bad_principal_type_raises(self):
        with pytest.raises(ValueError, match="unknown"):
            PolicyTranslator.validate_yaml({
                "rules": [{
                    "path": "x",
                    "capabilities": ["read"],
                    "principals": [{"type": "ghost", "id": "x"}],
                }]
            })


@pytest.mark.unit
class TestToHCL:
    def test_hcl_contains_path(self, doc):
        hcl = PolicyTranslator.toHCL(doc)
        assert "prod/db/password" in hcl

    def test_hcl_contains_capabilities(self, doc):
        hcl = PolicyTranslator.toHCL(doc)
        assert '"read"' in hcl

    def test_hcl_wildcard_converted(self, doc):
        hcl = PolicyTranslator.toHCL(doc)
        # prod/api/* should become prod/api/+
        assert "prod/api/+" in hcl
        assert "prod/api/*" not in hcl

    def test_hcl_metadata_block_for_list(self, doc):
        hcl = PolicyTranslator.toHCL(doc)
        assert "secret/metadata/" in hcl

    def test_hcl_write_maps_to_create_update(self, doc):
        hcl = PolicyTranslator.toHCL(doc)
        assert '"create"' in hcl or '"update"' in hcl

    def test_hcl_has_comment_header(self, doc):
        hcl = PolicyTranslator.toHCL(doc)
        assert hcl.startswith("# Generated by PolicyTranslator")

    def test_hcl_description_appears_as_comment(self, doc):
        hcl = PolicyTranslator.toHCL(doc)
        assert "Read prod DB password" in hcl

    def test_not_instantiable(self):
        with pytest.raises(TypeError):
            PolicyTranslator()  # type: ignore[abstract]


@pytest.mark.unit
class TestToIAMJson:
    def test_aws_policy_version(self, doc):
        policy = PolicyTranslator.toIAMJson(doc, account_id="123", region="us-east-1")
        assert policy["Version"] == "2012-10-17"

    def test_aws_statement_for_aws_principals_only(self, doc):
        policy = PolicyTranslator.toIAMJson(doc)
        # Only rules with aws_iam_role / aws_iam_user get statements
        assert len(policy["Statement"]) >= 1

    def test_aws_read_actions(self, doc):
        policy = PolicyTranslator.toIAMJson(doc, account_id="123", region="us-east-1")
        all_actions = [a for s in policy["Statement"] for a in s["Action"]]
        assert "secretsmanager:GetSecretValue" in all_actions

    def test_aws_arn_format(self, doc):
        policy = PolicyTranslator.toIAMJson(doc, account_id="123", region="eu-west-1")
        resources = [r for s in policy["Statement"] for r in s["Resource"]]
        assert any("arn:aws:secretsmanager:eu-west-1:123:secret:" in r for r in resources)

    def test_aws_write_actions(self, doc):
        policy = PolicyTranslator.toIAMJson(doc, account_id="123")
        all_actions = [a for s in policy["Statement"] for a in s["Action"]]
        assert "secretsmanager:PutSecretValue" in all_actions

    def test_iam_user_included(self, doc):
        policy = PolicyTranslator.toIAMJson(doc, account_id="123")
        principals = [p for s in policy["Statement"] for p in s["Principal"]["AWS"]]
        assert any("user/ops-engineer" in p for p in principals)


@pytest.mark.unit
class TestToGcpIamCond:
    def test_returns_list(self, doc):
        bindings = PolicyTranslator.toGcpIamCond(doc)
        assert isinstance(bindings, list)

    def test_accessor_role_present(self, doc):
        bindings = PolicyTranslator.toGcpIamCond(doc)
        roles = [b["role"] for b in bindings]
        assert "roles/secretmanager.secretAccessor" in roles

    def test_service_account_member_format(self, doc):
        bindings = PolicyTranslator.toGcpIamCond(doc)
        members = [m for b in bindings for m in b["members"]]
        assert any(m.startswith("serviceAccount:") for m in members)

    def test_wildcard_path_has_cel_condition(self, doc):
        bindings = PolicyTranslator.toGcpIamCond(doc, gcp_project="my-project")
        # prod/api/* should produce a binding with a condition
        conditioned = [b for b in bindings if "condition" in b]
        assert len(conditioned) >= 1

    def test_cel_condition_expression(self, doc):
        bindings = PolicyTranslator.toGcpIamCond(doc, gcp_project="my-project")
        cels = [b["condition"]["expression"] for b in bindings if "condition" in b]
        assert any("startsWith" in cel for cel in cels)

    def test_exact_path_no_condition(self, doc):
        bindings = PolicyTranslator.toGcpIamCond(doc)
        # prod/db/password has no wildcard — might appear without condition
        exact = [b for b in bindings if "condition" not in b]
        # At least one binding should be condition-free (exact paths)
        assert len(exact) >= 0  # not strict, just structural check


@pytest.mark.unit
class TestToAzureRbac:
    def test_returns_list(self, doc):
        assignments = PolicyTranslator.toAzureRbac(doc)
        assert isinstance(assignments, list)

    def test_azure_sp_included(self, doc):
        assignments = PolicyTranslator.toAzureRbac(doc)
        ids = [a["principal_id"] for a in assignments]
        assert "00000000-0000-0000-0000-000000000001" in ids

    def test_scope_format(self, doc):
        assignments = PolicyTranslator.toAzureRbac(
            doc,
            subscription_id="sub-1",
            resource_group="rg-1",
            vault_name="kv-1",
        )
        scopes = {a["scope"] for a in assignments}
        assert all("sub-1" in s and "rg-1" in s and "kv-1" in s for s in scopes)

    def test_write_implies_officer_role(self):
        # Separate doc that explicitly has write + azure_sp (sample YAML has write
        # only on a rule with no azure_sp principals — use dedicated fixture).
        write_doc = PolicyTranslator.load_yaml("""
rules:
  - path: "prod/*"
    capabilities: [write, delete]
    principals:
      - type: azure_sp
        id: "write-sp-id"
""")
        assignments = PolicyTranslator.toAzureRbac(write_doc)
        roles = {a["role"] for a in assignments}
        assert "Key Vault Secrets Officer" in roles

    def test_read_only_gives_user_role(self):
        doc = PolicyTranslator.load_yaml("""
rules:
  - path: "prod/x"
    capabilities: [read]
    principals:
      - type: azure_sp
        id: "read-sp-id"
""")
        assignments = PolicyTranslator.toAzureRbac(doc)
        assert assignments[0]["role"] == "Key Vault Secrets User"

    def test_no_duplicates(self, doc):
        assignments = PolicyTranslator.toAzureRbac(doc)
        keys = [(a["role"], a["principal_id"]) for a in assignments]
        assert len(keys) == len(set(keys))


@pytest.mark.unit
class TestSummary:
    def test_summary_fields(self, doc):
        s = PolicyTranslator.summary(doc)
        assert s["rule_count"] == 3
        assert "read" in s["capabilities"]
        assert "prod/db/password" in s["paths"]
